---
title: "Application of Central Limit Theorem to Exponential Distribution - Example"
author: "Amade Annissimo"
date: "December 2, 2015"
output: pdf_document
---
## Overview

This paper describes the application of Central Limit Theorem to the distribution of means of exponential distribution. The emphasis is put on empirical presentation of a problem, with a random sample of 1000 means and comparing their distribution with the theoretical distribution of the man and theoretical variance.


## Simulations

```{r, echo = TRUE}
n <- 1000
sampleSize <- 40
lambda <- 0.2
```

For the purpose of presentation, random sample of **`r n`** means of exponential distribution needs to be generated. Each mean is calculated based on **`r sampleSize`** values from exponential distribution with parameter lambda of **`r lambda`**. In turnn in order to obtain the sample, **`r n * sampleSize`** random numbers need to be generated.

Include English explanations of the simulations you ran, with the accompanying R code. Your explanations should make clear what the R code accomplishes.

## Sample Mean versus Theoretical Mean

Include figures with titles. In the figures, highlight the means you are comparing. Include text that explains the figures and what is shown on them, and provides appropriate numbers.

## Sample Variance versus Theoretical Variance

Include figures (output from R) with titles. Highlight the variances you are comparing. Include text that explains your understanding of the differences of the variances.

## Distribution

Via figures and text, explain how one can tell the distribution is approximately normal.

Here I can show the histogram based on the empirical distribution and draw a normal distribution curve on top of it, explaining how they are similar. 
In addition to that, references to proper statistical tests of normality will be useful.